services:
  app:
    build: .
    image: testkube_app
    container_name: testkube
    ports:
      - "8000:8000"
    depends_on:
      - datab

  datab:
    image: postgres:13-alpine
    container_name: testkube_db
    environment:
      POSTGRES_USER: dhawala
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: managedb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data  
volumes:
  db_data:
