{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Values.namespaces.name }}
{{- if .Values.secrets.type }}
type: {{ .Values.secrets.type }}
{{- end }}
{{- if .Values.secrets.data }}
data:
{{- if .Values.secrets.data.POSTGRES_USER }}
  POSTGRES_USER: {{ .Values.secrets.data.POSTGRES_USER | b64enc | quote }}
{{- end }}
{{- if .Values.secrets.data.POSTGRES_PASSWORD }}
  POSTGRES_PASSWORD: {{ .Values.secrets.data.POSTGRES_PASSWORD | toString | b64enc | quote }}
{{- end }}
{{- if .Values.secrets.data.POSTGRES_DB }}
  POSTGRES_DB: {{ .Values.secrets.data.POSTGRES_DB | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
