apiVersion: v1
kind: Secret
metadata: #USe to reference secret in pods
  name: db-secret
  namespace: testspace
type: Opaque # type of the secret (opaque means arbitrary user-defined data)
data:
  POSTGRES_USER: ZGhhd2FsYQ==       # Base64 for 'dhawala'
  POSTGRES_PASSWORD: MTIz           # Base64 for '123'
  POSTGRES_DB: VGVzdGJhc2U=        # Base64 for 'Testbase'
