apiVersion: v1
kind: Secret
metadata: 
  name: {{.Values.secret.name }}
type: {{.Values.secret.type }} 
data:
  POSTGRES_USER: {{.Values.secret.POSTGRES_USER }}       
  POSTGRES_PASSWORD: {{.Values.secret.POSTGRES_PASSWORD }}          
  POSTGRES_DB: {{.Values.secret.POSTGRES_DB }}        
  DATABASE_URL: {{.Values.secret.DATABASE_URL }}
  ADMIN1_ID: {{.Values.secret.ADMIN1_ID }}
  ADMIN1_USERNAME: {{.Values.secret.ADMIN1_USERNAME }}
  ADMIN1_PASSWORD: {{.Values.secret.ADMIN1_PASSWORD }}
  ADMIN1_NAME: {{.Values.secret.ADMIN1_NAME }}
  ADMIN1_EMAIL: {{.Values.secret.ADMIN1_EMAIL }}
  ADMIN2_ID: {{.Values.secret.ADMIN2_ID }}
  ADMIN2_USERNAME: {{.Values.secret.ADMIN2_USERNAME }}
  ADMIN2_PASSWORD: {{.Values.secret.ADMIN2_PASSWORD }}
  ADMIN2_NAME: {{.Values.secret.ADMIN2_NAME }}
  ADMIN2_EMAIL: {{.Values.secret.ADMIN2_EMAIL }}
