apiVersion: v1
kind: Secret
metadata: #USe to reference secret in pods
  name: db-secret
type: Opaque # type of the secret (opaque means arbitrary user-defined data)
data:
  POSTGRES_USER: ZGhhd2FsYQ==       # Base64 for 'dhawala'
  POSTGRES_PASSWORD: MTIz           # Base64 for '123'
  POSTGRES_DB: bWFuYWdlZGI=         # Base64 for 'managedb'
  DATABASE_URL: cG9zdGdyZXNxbCthc3luY3BnOi8vZGhhd2FsYToxMjNAcG9zdGdyZXMtc2VydmljZTo1NDMyL21hbmFnZWRi # Base64 for 'postgresql+asyncpg://dhawala:123@postgres-service:5432/managedb'
  ADMIN1_ID: MQ==  # Base64 for '1'
  ADMIN1_USERNAME: RGhhd2FsYQ==  # Base64 for 'Dhawala'
  ADMIN1_PASSWORD: MTIz  # Base64 for '123'
  ADMIN1_NAME: RGhhd2FsYSBSYWpha2FydW5h  # Base64 for 'Dhawala Rajakaruna'
  ADMIN1_EMAIL: ZGhhd2FsYUBnbWFpbC5jb20=  # Base64 for 'dhawala@gmail.com'
  ADMIN2_ID: Mg==  # Base64 for '2'
  ADMIN2_USERNAME: U2FuY2E=  # Base64 for 'Sanka'
  ADMIN2_PASSWORD: NDU2  # Base64 for '456'
  ADMIN2_NAME: U2FuY2EgUmFqYWthcnVuYQ==  # Base64 for 'Sanka Rajakaruna'
  ADMIN2_EMAIL: c2FuY2FAZ21haWwuY29t  # Base64 for 'sanka@gmail.com'